name: Quick Tests

on:
  push:
    branches:
      - main
    # Alternative: only build for tags.
    # tags:
    #   - '*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      # ADJUST THIS: install all dependencies (including pdoc)
      - run: pip install uv
      - run: uv sync --extra vlm
      - run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - run: which python && pip list
      - run: uv pip install pdoc
      - run: uv pip install -e ".[vlm]"
      - run: uv pip install vptq
      # ADJUST THIS: build your documentation into docs/.
      # We use a custom build script for pdoc itself, ideally you just run `pdoc -o docs/ ...` here.
      - run: |
          bash quick_tests.sh
