name: Quick tests

on:
  push:
    branches:
      - "**"
  # Optional: lets you run it manually from the Actions tab
  workflow_dispatch:

jobs:
  quick_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          
      - run: pip install uv
      - run: uv sync --extra vlm
      - run: |
          . .venv/bin/activate
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
          echo PATH=$PATH >> $GITHUB_ENV
      - run: uv pip install -e ".[vlm]"
      - run: chmod +x ./quick_tests.sh
      - run: which pip ; pip list
      - name: Run quick tests
        run: ./quick_tests.sh
